// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUDFStOTn9bl8ZUrIZlCkg1TeO8O53-H4',
    appId: '1:622594673667:web:b963a52a66bafe0ebad236',
    messagingSenderId: '622594673667',
    projectId: 'moviv1',
    authDomain: 'moviv1.firebaseapp.com',
    storageBucket: 'moviv1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBukK_e3VaTvGLPg8PpaFhYxcVOxuRirYs',
    appId: '1:622594673667:android:39d92ccf499027eebad236',
    messagingSenderId: '622594673667',
    projectId: 'moviv1',
    storageBucket: 'moviv1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzt0j_aZ3eOn07yvXZfK4yw4IXtp33OLw',
    appId: '1:622594673667:ios:27153a74ec328ae1bad236',
    messagingSenderId: '622594673667',
    projectId: 'moviv1',
    storageBucket: 'moviv1.appspot.com',
    iosClientId: '622594673667-e3o1tme14q7sng4v27m5ic1bguudp39l.apps.googleusercontent.com',
    iosBundleId: 'com.example.movi',
  );
}
